### ISSUE TITLE
Login page - determine host and port automatically

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/RESTFormsUI#19]
Currently defaults are `localhost` and `57772`. They should be determined automatically based on current UI url (user still should have an ability to edit them if he so wishes)

**Comment by eduard93** [comment]
And hide this advanced settings.

**Comment by evshvarov** [comment]
And add them to remote.html page

**Comment by MakarovS96** [comment]
Maybe location.hostname and location.port??? @eduard93 
[https://www.w3schools.com/js/js_window_location.asp](url)
